# https://numtide.github.io/devshell
imports = ["language.rust"]

[devshell]
packages = [
         "rust-analyzer"
]

[[commands]]
package = "devshell.cli"
help = "Per project developer environments"
