# https://numtide.github.io/devshell

[devshell]
packages = [
         "rust-analyzer"
]

[[commands]]
package = "devshell.cli"
help = "Per project developer environments"

[[commands]]
package = "rust-bin.stable.latest.default"
name = "cargo"
help = "control the rust environment, start builds etc."
